export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_FAILURE = 'GET_NEWS_FAILURE';

export const SET_NEWS_SUCCESS = 'SET_NEWS_SUCCESS';
export const SET_NEWS_REQUEST = 'SET_NEWS_REQUEST';
export const SET_NEWS_FAILURE = 'SET_NEWS_FAILURE';

export const REMOVE_NEWS_SUCCESS = 'REMOVE_NEWS_SUCCESS';
export const REMOVE_NEWS_REQUEST = 'REMOVE_NEWS_REQUEST';
export const REMOVE_NEWS_FAILURE = 'REMOVE_NEWS_FAILURE';
